### ISSUE TITLE
yvel and yacc in terms of width, but ypos in terms of height

### ISSUE THREAD

**Issue by PyryM** [workergnome/exquisite_donut#15]
Accelerations and velocities are defined in terms of the width, even for `yacc` and `yvel`, so that they mean the same thing in pixels/centimeters for both. However, `ypos` is inconsistently defined in terms of the height. This means that code is going to have to look like:

```
xpos += xvel;
ypos += (yvel / ASPECT_RATIO);
xvel += xacc;
yvel += yacc; // I almost divided by ASPECT_RATIO here too!
```

I think it would be simpler to let `ypos` also be defined in terms of width, so that it would range from 0-1.778 for portrait mode 1920x1080 monitors.

Even Rule 5.1 gets this wrong by saying:

> YPOS should be modified by adding YVEL to it.

(I'm working with Pras, btw)

**Comment by workergnome** [comment]
Talked to Liz and Nico, and they agree with you.  We're going to re-write the examples and the docs.
