### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by workergnome** [workergnome/exquisite_donut#2]
From @jmarsico: should this be 30? if i remember, i had trouble hitting 60fps in processing when i was a beginner.

**Comment by workergnome** [comment]
I checked, and the default in Processing is 60fps.  The way the spec is written, you could do a 30 FPS sketch, and be in spec, as long as you doubled the step distance.  Basically, update the particles twice, draw once.  (or did the math to accomplish the same thing.)

I'd be OK with changing this number, too, though.

**Comment by jmarsico** [comment]
there's a good chance that this memory of not hitting 60fps was the result of not knowing what i was doing and trying to deal with thousands and thousands of particles
