### ISSUE TITLE
Difficult to test given the existing rules

### ISSUE THREAD

**Issue by workergnome** [workergnome/exquisite_donut#6]
Since you can only have one application listening on a given port, you can only have one instance of this running per-computer.  

The issue is what happens when you send a particle off your left side—the message will be sent to yourself, but you won't be able to tell if it should be on your left or your right, because both your left and your right sides are yourself.  (Man, this is _confusing_ to try and write.)

So.  I'm thinking that if a particle message comes in from an ID that is equal to your own ID and the velocity is positive, assign it to the left side, otherwise the right side.

Any issues?

**Comment by jmarsico** [comment]
i like the signed velocity idea. now we can test on ourselves.

**Comment by workergnome** [comment]
Cool.  I'll close that pull request.
